# Generated by Django 4.2.7 on 2023-12-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
    ]
